#!/usr/bin/env ruby
# frozen_string_literal: true
$:.unshift File.dirname(__FILE__)+'/../lib'

require 'fileutils'

# Require ruby files from lib folder recursively
# lib_path = File.expand_path('../lib', __dir__)
# Dir[File.join(lib_path, '**', '*.rb')].each { |file| require file }
require_relative '../lib/mqtt_server.rb'

at_exit do
  puts 'App quiting'
end

app = MqttServer::Server.new

puts app